### ISSUE TITLE
docker-component on Makefile fails on otelsvc

### ISSUE THREAD

**Issue by etsangsplk** [open-telemetry/opentelemetry-service#48] opened 2019-06-24 23:02 UTC
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelsvc_linux -ldflags "-X github.com/open-telemetry/opentelemetry-service/internal/version.GitHash=2a40f54 " ./cmd/otelsvc
cp ./bin/ocotelsvc_linux ./cmd/ocotelsvc/
cp: directory ./cmd/ocotelsvc does not exist

Because:

docker-component is assuming all component has a "oc" prefix.

docker-otelsvc: 
	COMPONENT=otelsvc $(MAKE) docker-component <<--

**Comment by tigrannajaryan** [comment] 2019-06-24 23:35
I can reproduce the failure on `make docker-collector` but not on `make docker-otelsvc`. The later passes successfully.

**Comment by tigrannajaryan** [comment] 2019-06-24 23:37
@pjanotti Rather than trying to fix I suggest to remove target `docker-collector` from makefile. We only need the unified `docker-otelsvc`. 
Having `docker-collector` in the makefile is misleading and unnecessary.
Thoughts?

**Comment by pjanotti** [comment] 2019-06-24 23:48
I think it is a good idea since the collector is temporarily present just to help with compatibility tests, the real target is `otelsvc`.

**Comment by tigrannajaryan** [comment] 2019-06-24 23:51
Sounds good. I'll remove `docker-collector` target, but will keep `collector` which builds the binary and which can be used in compatibitity tests if needed (the testbed is executing the binary directly, it doesn't need the docker image).

**Comment by etsangsplk** [comment] 2019-06-25 00:06
$(GOOS) will be darwin if it is on Mac. 
otelsvc:
	mkdir -p ./cmd/otelsvc
	GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelsvc_$(GOOS) $(BUILD_INFO) ./cmd/otelsvc

But docker-component still looks for _linux ..
cp ./bin/$(COMPONENT)_linux  <---

**Comment by tigrannajaryan** [comment] 2019-06-25 00:17
@etsangsplk `docker-component` target does not depend on `otelsvc` target. Can you provide exact reproduction steps? Are you running `make docker-otelsvc` on Mac?

Also, where do you see `oc$(COMPONENT)`? It is nowhere in makefile.

**Comment by etsangsplk** [comment] 2019-06-25 00:20
Mine repo is old. It was removed 4 days ago. Sync to master and it is now fine.

https://github.com/open-telemetry/opentelemetry-service/commit/8772c908dd28b64617fd6b501583151d0c49ed7d

**Comment by tigrannajaryan** [comment] 2019-06-25 01:05
OK, good to know. Thanks for reporting the issue anyway. I am going to remove `docker-component` target to avoid confusion in the future.

**Comment by tigrannajaryan** [comment] 2019-06-25 01:06
Done, closing the issue.

**Closed by tigrannajaryan** 2019-06-25 01:06 UTC
