### ISSUE TITLE
test: TestExportProtocolViolations_nodelessFirstMessage

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-service#174] opened 2019-07-18 17:56 UTC
Failed in PR #173 
```
panic: Log in goroutine after TestExportProtocolViolations_nodelessFirstMessage has completed
goroutine 39 [running]:
testing.(*common).logDepth(0xc000294300, 0xc000026bc0, 0x18, 0x3)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:614
testing.(*common).Log(0xc000294300, 0xc000055f50, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:642 +0x79
github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1(0xc00002c150, 0xc000294300, 0x77359400, 0xc0002fb620)
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x203
created by github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fb
FAIL	github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics	0.198s
```

**Comment by songy23** [comment] 2019-08-08 17:06
Duplicate of https://github.com/open-telemetry/opentelemetry-service/issues/41.

**Closed by songy23** 2019-08-08 17:06 UTC
